// Auto-generated by build.mjs — do not edit by hand.
window.GIFT_PUBLIC = {
  "colors": {
    "bgStart": "#fbc2eb",
    "bgEnd": "#a6c1ee",
    "button": "#ff6b9d",
    "buttonHover": "#ff8fb1",
    "text": "#c2185b",
    "cardBack": "linear-gradient(135deg, #ff6b9d 0%, #c2185b 100%)"
  },
  "animations": {
    "floatDuration": "18s",
    "bounceSpeed": "0.5s"
  },
  "gate": {
    "hint": "Omg! we have a ___ situation.",
    "placeholder": "fill in the blank…",
    "unlockBtn": "Unlock 🔓",
    "wrongMsg": "Hmm, that's not it. Think harder, my love 💭"
  },
  "pageTitle": "💝"
};
window.GIFT_PAYLOAD = {"v":1,"salt":"ehN6RemDw26KL9rieykPvA==","iv":"dYvkd4Y93C+8I6+V","iter":200000,"ct":"SmHb9TZM3msy8YJ7P67ULctIfBP89duqJOSLysJIELzP2bNBqH46rRyiLQVctzlcS7ywvZUqClKFXQlF1wonsSudwrDJnJcbl1ytumv55wtTXK8yjmIcKnHyeACR+3M9GksBWQjafgSycqKvwo2xfJrxvx4SSXprKlHqHRQzxF8BuPau9XSURJWl1pX82I4VsyEZTs7NrJomArvz7ef0Ul2X7ufunHl7M+XUQHTcIoHT2clKMDpnJ11/7WBE2fea9kMRwkY7ISjfu4QXYojmiucdDEA4wOVr7ec/pp3oFoRbLEhe8Rx2IMCd/yznOahol7J3H/qtNQcPR0ZtYnKCKph9i7a3LjGwJijxpgQHKmGU3L0LfkZtgBrZV4EWyfmVygvNzl+cHvF9hu2a/fp3Fv760nuWj6j9NUMVKF+SUb3s/Dqaws7c7KNzLPc3DtX4Cai5+EHhTNLuJj04aXm5jSbY8k2oLJbGmY/jJfIaToHJcshfeiSpJacuSUWVWMfq+ju3qMvsbmKiVSkBXQVrv/w3t3Y/nnKV7rpNecGVicpI7celVc/JUwktoTwCeSsRrWtK8WBUSnX2zeBXaF28qQymopPa+BNxDIIbuDeMjZ652N6cO03RUBBJORWwvej/s6MfTBEMsZrguDcCIu5GURDvIJMZdvNn9SM4kaB+TV8LGAGXcjVN//QPt6bXHnKZhcz4G/nHPeBOpP0u4DFMG1zvB0dCrWYHHW+Jeg8dHdAuFVW5CBBGYwXrWJ1y5Cr0r2/bc4L9PCAuBSBHHiSX72XEpHNASOLnkRY/FdN3sMPkyyfpZnz4YCQ+i7k+4pwc2yZj9t5VG13KGZpn1oor+ows0P0NQTSq9ToksxTjPhXmtad2eqDU+TKxPy3mWQnXrW45NbKh0zd2G0RhkIkEsvsLLx5uC3KZVWny4YjULyAnqZKVJXdtdQ933XR6DDvHpg9xY2TeCORldUQAYjxICO1nA9xCFCU9bqJVIaf3Cd6o2SSCMA2Rfa8Y/vd6d00RCWSx+7JjYnu7fIIGybnM3qG+HPFiwA4dyvXy58uZSNTkSgexr/w5T2ep5Q3566tbiNA9SokEZEVAYN3C3BvI59i2CPb2P6EZzFgLMU8ZXG2nIrW5fcloxSR1+aVBhA/ezwh6aP10NbC83SUUTTg22zd0ZO1KFDd9EgMMwRc+smHm4/W0NxYzAt5Io3O64a6O8o7u0V5BPJAfVWY3yvOAT8HozHyKmK3UicnztPqVy70shwKH5OaukoxKA1cXueGTzZ+Rj43R43eBEfCh42HQy607/5Vl7vENJ46w+lSU2DLO23WNQeawjc0ktuUCJ7N0MeMIO11ynQsl6dQtrea2MXil6E4DQQY3b7ChcoT8tNu9nZbzZHJzvSungB04BK4QolE0vluL+CUFGroRwjGn9czsMvHyqv4xd8Dl8xhKBPh4M6anwydIvN5uUNsA3NiCRyrXk6U/Gm14DsiItXSvjyC4Zw2wpPchZBj9tzMocB7jhSCHGzCAwikFnGcELeMcOKoj8u82REQr4i0hBQgjyLu8n8FSpf217SDAoqplV0db+Ycn8T7rzDb2TK36I0TWfHLnoT9jO9e869GubylsxB35yuZRGz9hnwwbo3I="};
