// Auto-generated by build.mjs — do not edit by hand.
window.GIFT_PUBLIC = {
  "colors": {
    "bgStart": "#fbc2eb",
    "bgEnd": "#a6c1ee",
    "button": "#ff6b9d",
    "buttonHover": "#ff8fb1",
    "text": "#c2185b",
    "cardBack": "linear-gradient(135deg, #ff6b9d 0%, #c2185b 100%)"
  },
  "animations": {
    "floatDuration": "18s",
    "bounceSpeed": "1.0s"
  },
  "gate": {
    "hint": "Omg! we have a ___ situation.",
    "placeholder": "fill in the blank…",
    "unlockBtn": "Unlock 🔓",
    "wrongMsg": "Hmm, that's not it. Think harder, my love 💭"
  },
  "pageTitle": "💝"
};
window.GIFT_PAYLOAD = {"v":1,"salt":"vKeZnrKbbDZfTkGatrgJoA==","iv":"b24VvsEHBRKMMAFG","iter":200000,"ct":"clzOcgVOp+dUa9YH1mRRngRbZvmsdy/V8bQxivSTlVrv4d+hUTJMnDw7wJc+tt0bMFfsMpCWmuVje0RbowHTgiqGnm0Qb+6eYDcV9COlv6pKfM8lEuil5iBsNHGch5QI9X8SYq1WplJeJhWewyy7eJ4dmHY+5lSbMJ60ji5qkRArPc82al/cOPEsqB/lTY9X/nm3+OTl0EkoT/DYAfeeF2CzEkEk1LyctTEbBjhcNRATak1QBLd0zIHDHnx5OcjPLUGHCpolAab3i6vfSXidppfoFB5YjvtOp3k16zkxrFzqAfa3HxbGCLYhWwKizjKG/O5MiJFGCbh0MXW6PtR205rAZA0SSys+nKdRxT//cGUvmE1DbGOJlUaOhAK1WhyBWtLJtGJQgu1NuOv4E1XUbyBS+vUl5D2e9jlvCX7JzUvLE9dlxwiIRk9o9cEnPIHB+0sYk0dA3D2MYZXaElwxhN28KGrkBtY8gskOQ2I8xiYLDPhaExqPwKCgKRnXFuX08uO/mwiH5q3VLF7vW/VYPPTzONbr3JDyXQCLx7CPeflMZOnn91wDUl+ar2DQvQdFSzJLD61DGLHEaD7AOTXG82bPm3cQ8HATTGEhWEtf2HA/nEITr+JiYfpvM/JfRtj8hea2cKxR+iF9ezgtztOmzywPxIUoKnE4Z2tYjtl2mnyN9aIVDwQqmErhXCnLrdgqV0L4Jtt8yBc06j4aWwsNthRjaTljX0jZRRyS0tahoY/gEUK5sg9PuTDfM0d8bBHhiw4LTq173yhE3F96owyFop+fjsh+2mQZmVsT6FV3+xYak9Mt04A79RIEFf+pVIBtJHd9FzxMCyGJobITSouaqYwi0VdarLByFXWDqHMNZIBujQwUbE88HjZIHyItT+hxX+LI4vSzepcLa/WbO2W6llIUEchBYwnEr8UrHeqjpHewthBuAqq2hWe+nJz4lsQKP5Ev297y+iXcGgmM2uzEvXkatX3LL5YEScGda2f1YqCmebu4jilKCiiX0k9TCSIYtbzWDDoNq/XvtiFM18aSKpKPji2BNr+C0VH0BW0FQnl9k0WhsV8Ak35XOQ8FX4SREdrO6vwL5uJq+7utvK4GwbslmyxYA0pYgxw9+2wHwEg4pHmifLmF/qjzaoudev/JscaCW5QlKGNaGgqJQdSdD218zWLQmSje3rVBiyybw6+8Ia6Ri7FyooxNegq8Mo/8tDbZFI6y1VjpA0CXF3hgFhlYA4LkcHpXH7qiZVO/VrwnKulFvlmd3a20tUZIAiXyNekaIS51DcchBc2oDUFYFUhFojti5Hpp1ZG/kcK8f2rf/C/pncWvEK99BjStG+H0dRFp7ey7XeLgNMYHwCK6Oec5cd2lLHliv6ylwZoX3DKcDFw+8c5ZDv9FeA1VmHRPJZTU0ggInB0U+IbxcHh6TZZcl1A4ZYKdNHJV5fDMVRRxPbMITOcw5SAfJEe3cfO+trU06nLntIcV/wbvQZn1/fN6bJtVi6K3hpi8T95nc29EJMH4xthHG+jdM53JqbYG60tMxs8ZtQix5kVaDTfkXIQYFOnahGNVMoSWD4N77BB9U/8RnTMiVh+kQmud6rGCgGUxg07CGw20okWMPrT3RcanEBj2HEdWz1JdY8eymQaLIDgbcNUTo9hFZyE="};
