// Auto-generated by build.mjs — do not edit by hand.
window.GIFT_PUBLIC = {
  "colors": {
    "bgStart": "#fbc2eb",
    "bgEnd": "#a6c1ee",
    "button": "#ff6b9d",
    "buttonHover": "#ff8fb1",
    "text": "#c2185b",
    "cardBack": "linear-gradient(135deg, #ff6b9d 0%, #c2185b 100%)"
  },
  "animations": {
    "floatDuration": "18s",
    "bounceSpeed": "1.0s"
  },
  "gate": {
    "hint": "Omg! we have a ___ situation.",
    "placeholder": "fill in the blank…",
    "unlockBtn": "Unlock 🔓",
    "wrongMsg": "Hmm, that's not it. Think harder, my love 💭"
  },
  "pageTitle": "💝"
};
window.GIFT_PAYLOAD = {"v":1,"salt":"ns+UyZRS5vTKxsWeuLoEVw==","iv":"3/3MAARjXGPyQlAt","iter":200000,"ct":"TbOOTF5tBsU/a4wG/viyiy+5fqdWey964sX9X2Tkswp25DDZ6nJFfxmbyi4x0ZX0Ivf+I95njELEAuWnlxTEmILMEJENb1wd/q41DZOlDW5fmrL/TXOGI8ObfoWWqeJjcBLXltT5Eqdv93gyM/MoMztTp2838LhzBti3zr9779oIOttZ3qXDXY3EpSl4P4kzHqmxXhRMCr4kXaIuwKXXPImnOTHrMQI45MjF4bl/y2v0L0f7BGeloEyyYAKPTAG+Tf7nRbICtL1IKyqTsShwDHpfVsFccajYrcrzdPFbrBqSmmcj8PFdtI2v6zk7GHg8WtEHYqZKSbVDlb08czRumtKK2f0L2CmLN3Tr9OUri3+YzxgAeA+8a0ZhbTUCNpTyCkxUGPwWbdXyzR/pXgP9eRLjhEl0OOiTZScdPVp4s0Mhk/vQI3TcXT/NDnj5JwcmaYbuQAMcf4DDgpGR57WFGipAxkiPZ4qre/8iTMKXNUJAReDLjXyPlKQ8PUNc7Bwqey8IxphFV2PhudHrRUvILdBRc7IQmqeFzxRXe8eGtc7Gam/uBl1BM3hb9mpSOIZYF9LW4aP8E1ALE00cX9HezAjMLTGuJ4uCPxRyGsFuyFjuX0O1SsRSuRD0yVquMGfv57PnhVHbcf/HjsxtcKKeUzsh6hjQbYXHOPWveQNayEsg0xF5tlnPDbcyVKwZbBDYEbBcKiO81+cjMBoUo1FNJTv7KZuVrz40GcZIt7ziK/o5n3qdRbOE1YDfsglcmJTetB+4JwHNO1Sb8JZ9Ev3V/yQ58hJ4x855LzsZXWp2aMjHUnUm4WucSgFSyZTajBc4bU7GMQ8zqUkCtT/aoA1ArKuoH2KxiXoXZzJqTeE9WVeIdMFTzehJxtFrwRMmoP5PSYOQFBRDrzoIuTZrI+X/MnOtdTFi9XMS/uchUi05ms/FDebW27KWusSp7qn4QdzgjVQifpxB4xAqJA1nl3+a8Aj6jer7vHP1zSv43epsfF/A1/dFWkzTCp9BRt3MTkKyEdKIhl45sZjo2DUd7EloVOFUFeJE+GAGuibeIG6rwBNwFCRleqBzZdOIH5UERDgsrMzJq454g03TNbI2zKRQP8AdDt9incMf5OO4psWnks8zjmIlTM3QVsyeMPTMvEQh28i/j8X0LoY/u4dt4k5iDys0tBceHVEufCFUFlv5ilylFq7NZPoG89lMJnR6UrTPxoY86+qiLdWDsllDKM0B5Y9+XHT42YrOGyIMJoT5ZrDxI5L9po+ESZ7wlLydnfZmjjvTCdJvacHTmsRF/k2fpPc253XaLVfKiHjw2r9LOZAAzWy5Gcid6HYmdJYfKhPcpXydnU1dcS5nFGOaD8uih8zILMorGeNTbF2ZOxJDEPCRVEfxkAFPO4SuQK2B4D+bNuBacOJkxh1K5kXZ+eP+PnwrcS5yq12DZLf2M5AoUvzzG+zjBgK7BSsSpcKieRgQ8ibfw/rgO9KMuzu/j6IFgF1RbKFs++9hhUlkEiZylHkvf1fFwuSSTgsXmxrCW122RqeYwnVeY3KaC7lb6JF7eoOB4nLl5xFYMR6RDr3Wgdr/iWDG3pgcUebtKBAoYg5W3QKPvjO4KEATZKwNiZMt8BoGGrNq9sylBk7xlc74rM+BalOECSlXQNvubJA="};
